# Generated by Django 4.1.3 on 2023-02-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_historicalstore_changed_by_store_changed_by'),
        ('tool', '0007_historicaltool_changed_by_tool_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('StoreFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeFrom', to='store.store')),
                ('StoreTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeTo', to='store.store')),
                ('Tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.tool')),
            ],
        ),
    ]
