# Generated by Django 4.1.3 on 2023-02-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transfer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='created_at',
        ),
    ]
