# Generated by Django 4.1.3 on 2023-02-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_historicalstore_changed_by_store_changed_by'),
        ('transfer', '0004_remove_transfer_storeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='StoreTo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storeTo', to='store.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
