# Generated by Django 4.1.3 on 2023-02-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_transfer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='cancell',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
