# Generated by Django 4.1.3 on 2023-02-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_transfer_cancell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='cancell',
            field=models.BooleanField(default=False),
        ),
    ]
