# Generated by Django 4.2.2 on 2023-08-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_alter_transfer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='cancell',
        ),
    ]
