# Generated by Django 4.1.3 on 2022-12-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('CompanyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.company')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('numberTools', models.IntegerField(editable=False, null=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='typeID',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='inventoryID',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='model',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='movementID',
        ),
        migrations.AddField(
            model_name='tool',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='ssid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='tool',
            name='StoreID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sections.store'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sections.function'),
        ),
    ]
