# Generated by Django 4.1.3 on 2022-12-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_company_companystatistics_function_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companystatistics',
            old_name='statistics',
            new_name='statisticsLink',
        ),
    ]
