# Generated by Django 4.1.3 on 2023-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_historicalstore_changed_by_store_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstore',
            name='RealNumberTools',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='RealNumberTools',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
