# Generated by Django 4.1.3 on 2023-03-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstore',
            name='RealNumberTools',
        ),
        migrations.RemoveField(
            model_name='historicalstore',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='RealNumberTools',
        ),
        migrations.RemoveField(
            model_name='store',
            name='changed_by',
        ),
    ]
