# Generated by Django 4.1.3 on 2023-03-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_historicalstore_realnumbertools_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstore',
            name='RealNumberTools',
        ),
        migrations.RemoveField(
            model_name='historicalstore',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='RealNumberTools',
        ),
        migrations.RemoveField(
            model_name='store',
            name='changed_by',
        ),
    ]
