# Generated by Django 4.1.3 on 2023-03-17 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_remove_historicalstore_realnumbertools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstore',
            name='RealNumberTools',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstore',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='RealNumberTools',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
