# Generated by Django 4.2.2 on 2023-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_historicalstore_realnumbertools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstore',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
