# Generated by Django 4.2.2 on 2023-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_historicalstore_location_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstore',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
