# Generated by Django 4.2.2 on 2023-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_distribution_changed_by_historicaldistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicaldistribution',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
