# Generated by Django 4.2.2 on 2023-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0004_alter_distribution_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldistribution',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
