# Generated by Django 4.2.2 on 2023-08-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0005_distribution_is_transfer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historicaldistribution',
        ),
    ]
