# Generated by Django 4.1.3 on 2023-03-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_alter_function_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalfunction',
            name='changed_by',
        ),
    ]
