# Generated by Django 4.1.3 on 2023-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltool',
            name='reason_change',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='reason_change',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
