# Generated by Django 4.1.3 on 2023-02-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_historicaltool_created_at_historicaltool_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='reason_change',
            new_name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicaltool',
            name='reason_change',
        ),
    ]
