# Generated by Django 4.1.3 on 2023-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_rename_reason_change_tool_history_change_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='history_change_reason',
        ),
        migrations.AlterField(
            model_name='historicaltool',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
