# Generated by Django 4.1.3 on 2023-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_remove_tool_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltool',
            name='reason_change',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='reason_change',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltool',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
