# Generated by Django 4.1.3 on 2023-02-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_historicaltool_reason_change_tool_reason_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltool',
            name='reason_change',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='reason_change',
        ),
    ]
