# Generated by Django 4.1.3 on 2023-03-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_alter_tool_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltool',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='changed_by',
        ),
    ]
