# Generated by Django 4.2.2 on 2023-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_historicaltool_changed_by_tool_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltool',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltool',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
