# Generated by Django 4.2.2 on 2023-07-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_alter_historicaltool_ip_alter_historicaltool_mac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltool',
            name='StoreID',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='StoreID',
        ),
    ]
