# Generated by Django 4.1.3 on 2023-03-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_company_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='statisticsLink',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='statisticsLink',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
    ]
