# Generated by Django 4.1.3 on 2023-03-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0010_alter_company_statisticslink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='statisticsLink',
            field=models.URLField(blank=True, db_index=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='statisticsLink',
            field=models.URLField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
    ]
