# Generated by Django 4.2.2 on 2023-07-31 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0014_alter_historicaltool_changed_by_and_more'),
        ('store', '0011_remove_historicalstore_realnumbertools_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('operation', models.CharField(choices=[('اضافة', 'اضافة'), ('سحب', 'سحب')], default='اضافة', max_length=100)),
                ('changed_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeF', to='store.store')),
                ('store_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeT', to='store.store')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.tool')),
            ],
        ),
    ]
